name: Terraform Plan
on:
  - push
jobs:
  changed-dirs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: changed-files
        uses: tj-actions/changed-files@v27
        with:
          path: src
          dir_names: true
          json: true
      - run: echo ${{ steps.changed-files.outputs.all_changes_files }}
    outputs:
      changed-dirs: ${{ steps.changed-files.outputs.all_changes_files }}
  terraform-plan:
    runs-on: ubuntu-latest
    needs: changed-dirs
    strategy:
      matrix:
        directory: ${{ fromJson(needs.changed-dirs.outputs.changed-dirs) }}
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/304731433117/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'terraform@terraform-360104.iam.gserviceaccount.com'
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform plan -no-color
