name: Terraform Plan
on:
  - push
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/google/projects/terraform
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/304731433117/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'terraform@terraform-360104.iam.gserviceaccount.com'
      - run: cat "$GOOGLE_APPLICATION_CREDENTIALS"
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
      - run: terraform plan -no-color
