name: Terraform Plan
on:
  - push
jobs:
  changed-dirs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: changed-files
        uses: tj-actions/changed-files@v27
        with:
          files: |
            src/**/*.tf
            src/**/*.tfvars
      - run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
    outputs:
      changed-dirs: ${{ steps.changed-files.outputs.all_changes_files }}
  # terraform-plan:
  #   runs-on: ubuntu-latest
  #   needs: changed-dirs
  #   strategy:
  #     matrix:
  #       directory: ${{ fromJson(needs.changed-dirs.outputs.changed-dirs) }}
  #   defaults:
  #     run:
  #       working-directory: ${{ matrix.directory }}
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'
  #   steps:
  #     - uses: 'actions/checkout@v3'
  #     - uses: 'google-github-actions/auth@v0'
  #       with:
  #         workload_identity_provider: 'projects/304731433117/locations/global/workloadIdentityPools/github-pool/providers/github'
  #         service_account: 'terraform@terraform-360104.iam.gserviceaccount.com'
  #     - uses: hashicorp/setup-terraform@v2
  #     - run: terraform init
  #     - run: terraform plan -no-color
